name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.3.2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Deploy
      run: |
        cd infrastructure/terraform/
        terraform init
        terraform validate
        terraform apply -auto-approve

  prefect-deploy:
    name: Prefect Deploy
    needs: deploy
    runs-on: ubuntu-latest
    container:
      image: prefecthq/prefect:latest
    env:
      KEY: ${{ secrets.PREFECT_TENANT_API_KEY}}

    steps:
    - uses: actions/checkout@v2

    - name: Install Python requirements
      run: |
        cd scripts
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Authenticate to Prefect dependencies
      run: prefect cloud login -k $KEY

    - name: Register flow
      run: |
        cd scripts
        prefect register -p pipeline.py --project gomesproject
